### ISSUE TITLE
Add package to AUR

### ISSUE THREAD

**Issue by Tardog** [eNzyOfficial/lightdm-tty#2]
I've taken the liberty to create a PKGBUILD for this theme, since AUR support is already on the TODO list. It will be submitted to the AUR when it has been tested by several people. Feedback welcome!

**Comment by Tardog** [comment]
I got some feedback and improved the working PKGBUILD. This is the AUR package:
https://aur.archlinux.org/packages/lightdm-webkit2-theme-tty-git/

**Comment by eNzyOfficial** [comment]
Thanks for this, I'm not well versed in making PKGBUILDs, if you want to make a pull request I can merge it in for you!

**Comment by Tardog** [comment]
Thank you! Here you go: #3
