### ISSUE TITLE
Having other distro names

### ISSUE THREAD

**Issue by GixoXYZ** [eNzyOfficial/lightdm-tty#4]
It would be nicer if you include other distro names or no name at all.
tnx for your time, it's a great theme.

**Comment by eNzyOfficial** [comment]
If you're talking about the MOTD, check out here if you're interested in changing it:

https://github.com/eNzyOfficial/lightdm-tty/blob/master/js/commands.js#L266-L274

If you wish to take it out completely, you can strip out these lines here:

https://github.com/eNzyOfficial/lightdm-tty/blob/master/js/main.js#L46-L48

I hope this helps :)

That aside, you're more than welcome to make a pull request with additional functionality and I'll merge it in!

**Comment by GixoXYZ** [comment]
Thanks for your respond, It was helpful!
